name: AI Model Report

on:
  schedule:
    # Runs at 11:30 AM every day (UTC time)
    - cron: '30 11 * * *'
  workflow_dispatch: # Allows manual run

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AI Model Report
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLICKUP_API_KEY: ${{ secrets.CLICKUP_API_KEY }}
          CLICKUP_TASK_ID: ${{ secrets.CLICKUP_TASK_ID }}
        run: python full.py
