name: AI Model Report Updater

on:
  schedule:
    # Runs at 5:00 AM UTC every day
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  run-report-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: ⬇️ Checkout code
      uses: actions/checkout@v4

    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: 📦 Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: ⚙️ Run the AI Model Reporter Script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CLICKUP_API_KEY: ${{ secrets.CLICKUP_API_KEY }}
        CLICKUP_TASK_ID: ${{ secrets.CLICKUP_TASK_ID }}
      run: python full.py